name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    
permissions:
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm package

      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          path: ./*.vsix
          name: extension.vsix
      - uses: actions/attest-build-provenance@v2
        with:
          subject-name: extension.vsix
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
